version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports: 
      - "80:80"
    networks:
      - django-app-network
    restart: always 
    depends_on:
      - django

  db:
    container_name: mysql_container
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes: 
      - django-app-data:/var/lib/mysql
    networks:
      - django-app-network
    restart: always
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-proot"]
      interval: 10s
      retries: 5
      timeout: 5s 
      start_period: 60s

  django:
    image: "ads754792/djangocicd-django:latest"
    container_name: django_cont
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: 
      - ".env"
    restart: always
    depends_on: 
      - db
    networks:
      - django-app-network
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 60s

networks:
  django-app-network:

volumes:
  django-app-data:
